spring.application.name=api-gateway

# Config Server
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=api-gateway
