spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

jwt.secret=VehicleServiceManagementSystem2025SecretKeyForJWTTokenGenerationMustBe256BitsLongForHS256Algorithm
spring.cloud.config.enabled=false
# ============================================
# PUBLIC ENDPOINTS (No authentication)
# ============================================
api.public.endpoints=/user-service/api/auth/login,/user-service/api/auth/register/customer,/user-service/api/auth/register/admin,/user-service/api/auth/register/manager,/user-service/api/auth/register/technician,/service-management-service/vehicle/service-requests/.*/public-details

# ============================================
# LOGGING
# ============================================
logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.vehiclemanagement.apigateway=DEBUG