spring.application.name=inventory-service-management

# APPLICATION CONFIGURATION
#spring.application.name=inventory-service
server.port=8084

# MYSQL DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_service_db? useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=divya
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# EUREKA CLIENT CONFIGURATION
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}: ${random.value}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ACTUATOR ENDPOINTS
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# LOGGING CONFIGURATION
logging.level.root=INFO
logging.level.com.vehiclemanagement.inventory=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# APPLICATION INFO
#info.app.name=Inventory Management Service
#info.app.description=Simple Inventory Management for Vehicle Service Management System
#info.app.version=1.0.0