spring.application.name=user-service

# Config Server
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=6

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=user-service

# RabbitMQ (In case not in Git)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
